#!/usr/bin/env node
/**
 * hook-utils.js
 * Shared utility functions for hooks/*.js scripts.
 */

'use strict';
const fs             = require('fs');
const path           = require('path');
const { execSync }   = require('child_process');

// ---------------------------------------------------------------------------
// Session JSON block constants
// ---------------------------------------------------------------------------
const SESSION_JSON_START = '<!-- CLADE:SESSION:JSON';
const SESSION_JSON_END   = '-->';

/**
 * Reads the Claude Code hook input JSON from stdin and returns it.
 * Returns an empty object if parsing fails.
 * @returns {object}
 */
function readHookInput() {
  try {
    return JSON.parse(fs.readFileSync(0, 'utf8'));
  } catch (_) {
    return {};
  }
}

/**
 * Generates the template text for a session file.
 * @param {string} dateStr - Date string in YYYYMMDD format
 * @returns {string}
 */
function createSessionTemplate(dateStr) {
  return [
    `SESSION: ${dateStr}`,
    'AGENT: (not set)',
    '',
    '## Approaches That Worked (with evidence)',
    '(fill in with the /end-session command)',
    '',
    '## Approaches That Were Tried but Failed',
    '(not filled in)',
    '',
    '## Approaches Not Yet Tried',
    '(not filled in)',
    '',
    '## Remaining Tasks',
    '(not filled in)',
  ].join('\n');
}

/**
 * Generates a Markdown section string from a facts object.
 * @param {{ recordedAt: string, bashCount: number, errCount: number, recentErrors: string[] }} factsObj
 * @returns {string}
 */
function buildFactsSection(factsObj) {
  const { recordedAt, bashCount, errCount, recentErrors } = factsObj;
  const lines = [
    '## Facts Log (auto-generated / stop.js)',
    `- Recorded at: ${recordedAt}`,
    `- Bash commands executed: ${bashCount}`,
    `- Errors: ${errCount}`,
    '- Recent error commands:',
  ];
  if (recentErrors.length === 0) {
    lines.push('  - (none)');
  } else {
    for (const cmd of recentErrors) {
      lines.push(`  - ${cmd}`);
    }
  }
  return lines.join('\n');
}

/**
 * Replaces the "## Facts Log (auto-generated / stop.js)" section in tmpContent.
 * Appends to the end if the section does not exist (idempotent).
 * @param {string} tmpContent - Existing session file text
 * @param {string} factsSection - Section string generated by buildFactsSection
 * @returns {string}
 */
function upsertFactsSection(tmpContent, factsSection) {
  const HEADER = '## Facts Log (auto-generated / stop.js)';
  const headerIndex = tmpContent.indexOf(HEADER);
  if (headerIndex === -1) {
    // Append to end, but insert before JSON block if one exists
    const jsonIdx = tmpContent.indexOf('\n' + SESSION_JSON_START);
    if (jsonIdx !== -1) {
      return tmpContent.slice(0, jsonIdx + 1) + factsSection + '\n\n' + tmpContent.slice(jsonIdx + 1);
    }
    const separator = tmpContent.endsWith('\n') ? '\n' : '\n\n';
    return tmpContent + separator + factsSection + '\n';
  }
  // Detect end of section: next `## ` header, JSON block marker, or end of file
  const nextSection = tmpContent.indexOf('\n## ', headerIndex + 1);
  const jsonBlock  = tmpContent.indexOf('\n' + SESSION_JSON_START, headerIndex + 1);

  let sectionEnd;
  if (nextSection === -1 && jsonBlock === -1) {
    // Section continues to end of file
    return tmpContent.slice(0, headerIndex) + factsSection + '\n';
  } else if (nextSection === -1) {
    sectionEnd = jsonBlock;
  } else if (jsonBlock === -1) {
    sectionEnd = nextSection;
  } else {
    sectionEnd = Math.min(nextSection, jsonBlock);
  }
  return tmpContent.slice(0, headerIndex) + factsSection + '\n' + tmpContent.slice(sectionEnd + 1);
}

// ---------------------------------------------------------------------------
// Session JSON block
// ---------------------------------------------------------------------------

/**
 * Builds a CLADE:SESSION:JSON block string from session data.
 * @param {object} data
 * @returns {string}
 */
function buildSessionJsonBlock(data) {
  return SESSION_JSON_START + '\n' + JSON.stringify(data, null, 2) + '\n' + SESSION_JSON_END;
}

/**
 * Extracts and parses the CLADE:SESSION:JSON block from a .tmp file's content.
 * Returns null if the block does not exist or cannot be parsed.
 * @param {string} content - session file content
 * @returns {object|null}
 */
function parseSessionJsonBlock(content) {
  const startIdx = content.indexOf(SESSION_JSON_START);
  if (startIdx === -1) return null;

  const jsonStart = startIdx + SESSION_JSON_START.length;
  const endIdx = content.indexOf(SESSION_JSON_END, jsonStart);
  if (endIdx === -1) return null;

  const jsonStr = content.slice(jsonStart, endIdx).trim();
  try {
    return JSON.parse(jsonStr);
  } catch (_) {
    return null;
  }
}

/**
 * Replaces the CLADE:SESSION:JSON block in tmpContent.
 * Appends to the end if the block does not exist (idempotent).
 * @param {string} tmpContent - existing session file text
 * @param {object} data - JSON data to write
 * @returns {string}
 */
function upsertSessionJsonBlock(tmpContent, data) {
  const block = buildSessionJsonBlock(data);
  const startIdx = tmpContent.indexOf(SESSION_JSON_START);
  if (startIdx === -1) {
    const separator = tmpContent.endsWith('\n') ? '\n' : '\n\n';
    return tmpContent + separator + block + '\n';
  }
  const jsonStart = startIdx + SESSION_JSON_START.length;
  const endIdx = tmpContent.indexOf(SESSION_JSON_END, jsonStart);
  if (endIdx === -1) {
    // Malformed block — truncate from start and re-append at end
    return tmpContent.slice(0, startIdx).trimEnd() + '\n\n' + block + '\n';
  }
  const blockEnd = endIdx + SESSION_JSON_END.length;
  const after = tmpContent.slice(blockEnd);
  return tmpContent.slice(0, startIdx) + block + (after.startsWith('\n') ? after : '\n' + after);
}

/**
 * Returns true if the current process is running inside a git worktree.
 * Compares --git-dir and --git-common-dir; they differ when in a worktree.
 * @returns {boolean}
 */
function isWorktree() {
  try {
    const gitDir    = execSync('git rev-parse --git-dir',        { encoding: 'utf8' }).trim();
    const commonDir = execSync('git rev-parse --git-common-dir', { encoding: 'utf8' }).trim();
    return gitDir !== commonDir;
  } catch (_) {
    return false;
  }
}

/**
 * Returns the main repository root even when called from a worktree.
 * Uses git rev-parse --git-common-dir to locate the main .git directory.
 * @returns {string}
 */
function getProjectRoot() {
  try {
    const gitCommonDir = execSync('git rev-parse --git-common-dir', { encoding: 'utf8' }).trim();
    const absGitDir = path.isAbsolute(gitCommonDir)
      ? gitCommonDir
      : path.join(process.cwd(), gitCommonDir);
    return path.dirname(absGitDir);
  } catch (_) {
    return process.cwd();
  }
}

module.exports = {
  readHookInput,
  isWorktree,
  getProjectRoot,
  createSessionTemplate,
  buildFactsSection,
  upsertFactsSection,
  buildSessionJsonBlock,
  parseSessionJsonBlock,
  upsertSessionJsonBlock,
};
